services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: dev
    command: yarn workspace frontend dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/frontend/.next
    environment:
      CHOKIDAR_USEPOLLING: "1"
      NEXT_TELEMETRY_DISABLED: "1"
    networks:
      - app_network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: dev
    command: yarn workspace backend dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "1"
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3001:3001"
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
