openapi: 3.0.0
info:
  title: Musiversal Song Library API
  version: 1.0.0
paths:
  /songs:
    get:
      summary: Get list of songs
      operationId: get
      responses:
        '200':
          description: List of songs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Song'
                additionalProperties: false

    post:
      summary: Add a new song
      operationId: post
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/NewSong'
      responses:
        '201':
          description: Song created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Song'

  /songs/{id}:
    delete:
      summary: Delete a song by ID
      operationId: delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            additionalProperties: false
      responses:
        '204':
          description: Song deleted

components:
  schemas:
    Song:
      type: object
      required:
        - id
        - name
        - artist
        - imageUrl
      additionalProperties: false
      properties:
        id:
          type: string
        name:
          type: string
        artist:
          type: string
        imageUrl:
          type: string

    NewSong:
      type: object
      required:
        - name
        - artist
      #        - image # express-openapi validates the request body against the OpenAPI schema before multer populates req.file
      additionalProperties: false
      properties:
        name:
          type: string
        artist:
          type: string
        image:
          type: string
          format: binary
